//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnotherTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public string link { get; set; }
        public string bookname { get; set; }
        public string photolink { get; set; }
        public byte[] photo { get; set; }
        public string type { get; set; }
    }
}
